// Code generated by mockery v2.46.1. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "stori/internal/summary/domain"

	mock "github.com/stretchr/testify/mock"
)

// SendEmailUC is an autogenerated mock type for the SendEmailUC type
type SendEmailUC struct {
	mock.Mock
}

// Exec provides a mock function with given fields: ctx, summary
func (_m *SendEmailUC) Exec(ctx context.Context, summary domain.Summary) error {
	ret := _m.Called(ctx, summary)

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Summary) error); ok {
		r0 = rf(ctx, summary)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSendEmailUC creates a new instance of SendEmailUC. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSendEmailUC(t interface {
	mock.TestingT
	Cleanup(func())
}) *SendEmailUC {
	mock := &SendEmailUC{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
